# Generated by Django 3.1.5 on 2021-04-18 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210224_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 23, 3, 28, 534158, tzinfo=utc)),
        ),
    ]
