# Generated by Django 4.1.4 on 2022-12-19 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_auto_20221219_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 13, 46, 12, 435528, tzinfo=datetime.timezone.utc)),
        ),
    ]
