# Generated by Django 4.1.4 on 2022-12-19 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superintendent',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 13, 51, 12, 433722, tzinfo=datetime.timezone.utc)),
        ),
    ]
