# Generated by Django 4.1.4 on 2022-12-21 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 23, 12, 29, 54, 63170, tzinfo=datetime.timezone.utc)),
        ),
    ]
