# Generated by Django 4.1.4 on 2022-12-23 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_alter_customuser_activate_key_expires_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 11, 52, 49, 964668, tzinfo=datetime.timezone.utc)),
        ),
    ]
