# Generated by Django 4.1.4 on 2022-12-23 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=150, verbose_name='Наименование')),
                ('full_name', models.CharField(default='', max_length=250, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, default='', max_length=13, verbose_name='ОГРН')),
                ('juridical_address', models.TextField(blank=True, default='', verbose_name='Юридический адрес')),
                ('physical_address', models.TextField(blank=True, default='', verbose_name='Физический адрес')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_code',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Персональный код'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 14, 15, 26, 356416, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.organisation', verbose_name='Организация'),
        ),
    ]
