# Generated by Django 4.1.4 on 2022-12-28 13:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_alter_bugreport_bug_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='bug_report_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 13, 57, 19, 859046, tzinfo=datetime.timezone.utc)),
        ),
    ]
