# Generated by Django 4.1.4 on 2023-01-12 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0022_alter_bugreport_bug_report_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 7, 55, 17, 479849, tzinfo=datetime.timezone.utc)),
        ),
    ]
