# Generated by Django 4.1.4 on 2023-01-12 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 9, 45, 3, 190330, tzinfo=datetime.timezone.utc)),
        ),
    ]
