# Generated by Django 4.1.4 on 2023-01-12 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 11, 18, 27, 991412, tzinfo=datetime.timezone.utc)),
        ),
    ]
