# Generated by Django 4.1.4 on 2023-01-12 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0025_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 14, 44, 34, 808659, tzinfo=datetime.timezone.utc)),
        ),
    ]
