# Generated by Django 4.1.5 on 2023-01-27 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0026_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 12, 33, 14, 983871, tzinfo=datetime.timezone.utc)),
        ),
    ]
