# Generated by Django 4.1.5 on 2023-02-18 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0027_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 14, 36, 53, 75563, tzinfo=datetime.timezone.utc)),
        ),
    ]
