# Generated by Django 4.1.5 on 2023-02-19 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 21, 18, 10, 32, 691254, tzinfo=datetime.timezone.utc)),
        ),
    ]
