# Generated by Django 4.1.7 on 2024-02-18 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0029_alter_customuser_activate_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activate_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 9, 56, 32, 561975, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
