# Generated by Django 4.1.7 on 2024-02-18 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0030_alter_customuser_activate_key_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activate_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 2, 20, 14, 48, 50, 459011, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
