# Generated by Django 4.1.7 on 2024-02-19 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0031_alter_customuser_activate_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 7, 45, 48, 690248, tzinfo=datetime.timezone.utc)),
        ),
    ]
