# Generated by Django 3.1.5 on 2021-04-25 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0006_auto_20210420_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_date', models.DateField(default='01.01.2000', verbose_name='Дата')),
                ('examiner',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL,
                                   verbose_name='Экзаменатор')),
                ('test_module',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test',
                                   verbose_name='Модуль')),
            ],
        ),
    ]
