# Generated by Django 3.1.5 on 2022-12-19 08:42

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210518_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uuid', models.CharField(max_length=4, verbose_name='УИН Студента')),
                ('exam_record', models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Файл документа')),
                ('exam_report', models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Файл документа')),
                ('task_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Отчеты',
                'verbose_name_plural': 'Отчет',
            },
        ),
    ]
