# Generated by Django 3.1.5 on 2022-12-19 10:55

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='exam_report2',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Файл документа 2'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='exam_record',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Аудиозапись'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='exam_report',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Файл документа 1'),
        ),
    ]
