# Generated by Django 3.1.5 on 2022-12-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20221219_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='exam_report',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='exam_report2',
        ),
        migrations.AddField(
            model_name='reporting',
            name='ers',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Оценка экзаменатора'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='ers_time',
            field=models.DateField(blank=True, null=True, verbose_name='Старт времени оценки экзаменатора'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_person', to=settings.AUTH_USER_MODEL, verbose_name='Экзаминатор'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='first_reiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_reiter_person', to=settings.AUTH_USER_MODEL, verbose_name='Рейтер'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='first_rss_time',
            field=models.DateField(blank=True, null=True, verbose_name='Старт времени оценки первого рейтера'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='rrs_first',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Оценка рейтера 1'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='rrs_second',
            field=models.FileField(blank=True, upload_to=tasks.models.directory_path, verbose_name='Оценка рейтера 2'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='second_reiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_reiter_person', to=settings.AUTH_USER_MODEL, verbose_name='Рейтер'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='second_rss_time',
            field=models.DateField(blank=True, null=True, verbose_name='Старт времени оценки второго рейтера'),
        ),
    ]
