# Generated by Django 3.1.5 on 2022-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20221219_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='ers_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт времени оценки экзаменатора'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='first_rss_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт времени оценки первого рейтера'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='second_rss_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт времени оценки второго рейтера'),
        ),
    ]
