# Generated by Django 4.1.4 on 2022-12-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20221219_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='task_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача'),
        ),
    ]
