# Generated by Django 4.1.4 on 2022-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_reporting_completed_alter_reporting_task_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='student_uuid',
            field=models.CharField(max_length=4, verbose_name='Уникальный номер экзаменуемого'),
        ),
    ]
