# Generated by Django 4.1.4 on 2022-12-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_reporting_student_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporting',
            options={'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
