# Generated by Django 4.1.4 on 2022-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_reporting_options_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_reporting',
            field=models.BooleanField(default=False, verbose_name='Создать отчет'),
        ),
    ]
