# Generated by Django 4.1.4 on 2022-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_reporting_ers_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='reporting_visible',
            field=models.BooleanField(default=True, verbose_name='Видимость в списке'),
        ),
    ]
