# Generated by Django 4.1.4 on 2022-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_reporting_first_reiter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporting',
            name='ers_time',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='first_rss_time',
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='second_rss_time',
        ),
        migrations.AddField(
            model_name='reporting',
            name='ers_time_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание оценки экзаменатора'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='ers_time_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало оценки экзаменатора'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='first_rss_time_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание оценки первого рейтера'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='first_rss_time_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало оценки первого рейтера'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='second_rss_time_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание оценки второго рейтера'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='second_rss_time_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало оценки второго рейтера'),
        ),
    ]
