# Generated by Django 4.1.4 on 2022-12-28 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_reporting_ers_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='visible_date_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='visible_date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
