# Generated by Django 4.1.4 on 2023-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_email_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='first_reiter_email_send',
            field=models.BooleanField(default=False, verbose_name='Отправлено письмо'),
        ),
        migrations.AddField(
            model_name='reporting',
            name='second_reiter_email_send',
            field=models.BooleanField(default=False, verbose_name='Отправлено письмо'),
        ),
    ]
