# Generated by Django 4.1.4 on 2023-01-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_reporting_first_reiter_email_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_uuid',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Уникальный номер экзаменуемого'),
        ),
    ]
