# Generated by Django 4.1.5 on 2023-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_task_student_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Признак удаления'),
        ),
    ]
