# Generated by Django 4.1.5 on 2023-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_field',
            field=models.FileField(upload_to='', verbose_name='MP3 файл'),
        ),
    ]
