# Generated by Django 4.1.7 on 2024-02-18 14:48

import django.core.validators
from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0024_alter_reporting_task_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporting",
            name="ers",
            field=models.FileField(
                blank=True,
                upload_to=tasks.models.directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("xlsx", "xls")
                    )
                ],
                verbose_name="Оценка экзаменатора",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="exam_record",
            field=models.FileField(
                blank=True,
                upload_to=tasks.models.directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("mp3", "m4a")
                    )
                ],
                verbose_name="Аудиозапись",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="rrs_first",
            field=models.FileField(
                blank=True,
                upload_to=tasks.models.directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("xlsx", "xls")
                    )
                ],
                verbose_name="Оценка рейтера 1",
            ),
        ),
        migrations.AlterField(
            model_name="reporting",
            name="rrs_second",
            field=models.FileField(
                blank=True,
                upload_to=tasks.models.directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("xlsx", "xls")
                    )
                ],
                verbose_name="Оценка рейтера 2",
            ),
        ),
    ]
