# Generated by Django 4.1.7 on 2024-05-02 12:14

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0025_alter_reporting_ers_alter_reporting_exam_record_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        upload_to=tasks.models.exam_directory_path,
                        verbose_name="MP3 файл",
                    ),
                ),
            ],
        ),
    ]
