# Generated by Django 3.1.5 on 2021-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0004_auto_20210224_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
    ]
